source "https://rubygems.org"

# Use reek for code quality
gem 'reek'

# Use pry for debugging
gem 'pry'

# Use ruby-lint for detecting compiler errors
gem 'ruby-lint'

# Use awesome print for easier debugging
gem 'awesome_print'