require 'awesome_print'
require 'byebug'
require 'xxhash'
require 'set'

require_relative 'characteristics_matrix'
require_relative 'signature_matrix'
require_relative 'comparison_file'
require_relative 'locality_hasher'
require_relative 'file_reader'
require_relative 'min_hasher'
require_relative 'hash_table'
require_relative 'comparator'
require_relative 'shingler'
